<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>Rbf.ProtoTest</RootNamespace>
    <AssemblyName>RbfProtoTest</AssemblyName>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Core" Version="2.46.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RbfProtocol\RbfProtocol.csproj" />
  </ItemGroup>

</Project>
